name: Check code style
on: push
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          code-version: 18
          cashe: 'npm'
          cashe-dependency-path: '**/package-lock.json'
      - run: npm ci
      - run: npm run lint
      - run: npm run format
